### ISSUE TITLE
How to force the modal to open over the current state

### ISSUE THREAD

**Issue by intensite** [nonplus/angular-ui-router-uib-modal#6]
I am trying to create a change password dialog using angular-ui-router-uib-modal from a link in a top navbar. 

However, I would like the new dialog to appear over whatever screen "state" it is called.  

Right now, the dialog is placed over itself unless I specify a parent state using the dot notation.

Is this possible?

**Comment by nonplus** [comment]
Sorry, this isn't possible using this plugin (unless you declared the "change password" as a child of all other states).  If you want to be able to show the model on top of an arbitrary state, you'll have to implement it using the traditional `$uibModal.open()` rather than as a modal state.

FWIW, in my applications, I use a top-level "settings" state for this - not a big deal because changing passwords is such an infrequent operation.
